### ISSUE TITLE
Failed to install phantomjs-prebuilt@2.1.14 with Node 0.12.17

### ISSUE THREAD

**Issue by falsandtru** [twada/power-assert-keeper#18]
It have failed by upstream bug.

https://travis-ci.org/twada/power-assert-keeper/jobs/183192437#L342-L386
https://github.com/Medium/phantomjs/issues/660

cc @twada

**Comment by twada** [comment]
[Troubleshooting guide](https://github.com/Medium/phantomjs#installation-fails-with-error-read-econnreset-or-error-connect-etimedout) told us that we should try again on `read ECONNRESET`. So, shall we try the build again?

**Comment by falsandtru** [comment]
Of course I can retry the build, but old versions don't failed for a long time. So I suspect the phantomjs.

https://travis-ci.org/twada/power-assert-keeper/builds

**Comment by twada** [comment]
Ah, Understood.

**Comment by falsandtru** [comment]
As a note, I didn't retry the build on the cron jobs listed on the build history for now.

**Comment by falsandtru** [comment]
I guess this is a language problem, or legacy support problem. I abandon Node 0.12.

**Comment by twada** [comment]
Agreed 👍
