### ISSUE TITLE
Breaking of karma-espower-preprocessor

### ISSUE THREAD

**Issue by falsandtru** [twada/power-assert-keeper#21]
https://travis-ci.org/twada/power-assert-keeper/jobs/320195010#L1098

@twada @vvakame Can you take a look?

**Comment by twada** [comment]
@falsandtru Sorry for late response, I'll take a look 👀

**Comment by twada** [comment]
@falsandtru Would you test [this branch](https://github.com/power-assert-js/karma-espower-preprocessor/pull/4)?
